### ISSUE TITLE
Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by trinhdinhdungcntt** [mhrst/bottom_sheet_bar#14]

**Comment by sanrixue** [comment]
我也遇到了相同的问题

**Comment by sanrixue** [comment]
bottom_sheet_bar: 2.1.1 使用2.1.1版本 不要使用 2.2.0版本

**Comment by mhrst** [comment]
Version `2.2.0` requires Flutter 3.0+ where `SchedulerBinding` is non-nullable. The pubspec.yaml for `2.2.0` does not reflect that and needs to be updated.

`2.2.1` will set the correct Flutter sdk constraint
