### ISSUE TITLE
Add Elevation or Shadow into Widget?

### ISSUE THREAD

**Issue by caturbgs** [mhrst/bottom_sheet_bar#6]
Are there any ways to add drop shadow into BottomSheet either in collapse or expand state?

**Comment by mhrst** [comment]
I added a `boxShadows` param to the `BottomSheetBar` widget in version: `2.0.1`:

Example:
```
          boxShadows: [
            BoxShadow(
              color: Colors.grey.withOpacity(0.5),
              spreadRadius: 5.0,
              blurRadius: 32.0,
              offset: Offset(0, 0),
            ),
          ],
```

**Comment by caturbgs** [comment]
> I added a `boxShadows` param to the `BottomSheetBar` widget in version: `2.0.1`:
> 
> Example:
> 
> ```
>           boxShadows: [
>             BoxShadow(
>               color: Colors.grey.withOpacity(0.5),
>               spreadRadius: 5.0,
>               blurRadius: 32.0,
>               offset: Offset(0, 0),
>             ),
>           ],
> ```

Woah thank you very much, looks pretty nice
